### ISSUE TITLE
The type of the package

### ISSUE THREAD

**Issue by samuelcygnus** [pinoox/numera#2]
Hello there,

The json composer file needs an adjustment in the type parameter, from "project" to "library".

This affects the installation suggestion in packagist org
composer create-project pinoox/numera
instead of:
composer require pinoox/numera

https://getcomposer.org/doc/04-schema.md#type

**Comment by yoosefap** [comment]
Hi there,

Thank you for catching that! I’ll update the type parameter in the composer file to "library" so it aligns correctly with the installation suggestion on Packagist.

I appreciate you pointing this out.
